export const ACTION_INPUT_USER = 'ACTION_INPUT_USER'
export const ACTION_INPUT_REPO = 'ACTION_INPUT_REPO'

export const ACTION_REQUEST_ISSUES = 'ACTION_REQUEST_ISSUES'
export const ACTION_FETCH_ISSUES = 'ACTION_FETCH_ISSUES'
export const ACTION_FETCH_ISSUES_OK = 'ACTION_FETCH_ISSUES_OK'
export const ACTION_FETCH_ISSUES_FAIL = 'ACTION_FETCH_ISSUES_FAIL'

export const ACTION_FETCH_REPOS = 'ACTION_FETCH_REPOS'
export const ACTION_FETCH_REPOS_OK = 'ACTION_FETCH_REPOS_OK'
export const ACTION_FETCH_REPOS_FAIL = 'ACTION_FETCH_REPOS_FAIL'

export const ACTION_REQUEST_ISSUE = 'ACTION_REQUEST_ISSUE'
export const ACTION_FETCH_ISSUE = 'ACTION_FETCH_ISSUE'
export const ACTION_FETCH_ISSUE_OK = 'ACTION_FETCH_ISSUE_OK'
export const ACTION_FETCH_ISSUE_FAIL = 'ACTION_FETCH_ISSUE_FAIL'