export const ACTION_INPUT_USER = 'ACTION_INPUT_USER'
export const ACTION_INPUT_REPO = 'ACTION_INPUT_REPO'
export const ACTION_INPUT_SEARCH = 'ACTION_INPUT_SEARCH'

export const ACTION_FETCH_ISSUES = 'ACTION_FETCH_ISSUES'
export const ACTION_FETCH_ISSUES_OK = 'ACTION_FETCH_ISSUES_OK'
export const ACTION_FETCH_ISSUES_FAIL = 'ACTION_FETCH_ISSUES_FAIL'

export const ACTION_FETCH_REPOS = 'ACTION_FETCH_REPOS'
export const ACTION_FETCH_REPOS_OK = 'ACTION_FETCH_REPOS_OK'
export const ACTION_FETCH_REPOS_FAIL = 'ACTION_FETCH_REPOS_FAIL'