export const ACTION_INPUT_USER = 'ACTION_INPUT_USER'
export const ACTION_INPUT_REPO = 'ACTION_INPUT_REPO'
export const ACTION_INPUT_SEARCH = 'ACTION_INPUT_SEARCH'
export const ACTION_FETCH_ISSUES_OK = 'ACTION_FETCH_ISSUES_OK'